[package]
name = "encoding"
version = "0.1.0"
authors = ["Kris Liu <liuqi0611@126.com>"]
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "encoding"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.2.0"

[dependencies]
neon = "0.2.0"
